[versions]
android-gradle-plugin = "8.10.0"
detekt = "1.23.8"
kotlin = "2.3.10"
dokka = "2.1.0"

compose = "1.10.0"

coil = "3.3.0"
ktor = "3.4.0"

intellij-markdown = "0.7.3"

kotlinx-benchmark = "0.4.14"

[libraries]
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
ktor-engine-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-engine-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-engine-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
intellij-markdown = { module = "org.jetbrains:markdown", version.ref = "intellij-markdown" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
kotlinx-benchmark = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark"}

android-libraryGradlePlugin = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "android-gradle-plugin" }
kotlin-multiplatformGradlePlugin = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
